/*
    @author: Chas Shipman   Jan 2019
*/

#include "type.h"

//keywords
char *VAR = "VAR";	char *FUNCTION = "FUNCTION";	char *CLASS = "CLASS";
char *ID = "ID";

char *IF = "IF";	char *ELSE = "ELSE";	char *WHILE = "WHILE";	char *FOR = "FOR";

char *INTEGER = "INTEGER";	char *REAL = "REAL";
char *CHARACTER = "CHAR";	char *STRING = "STRING";

char *PRINT= "PRINT"; char *PRINTLN = "PRINTLN";
char *END_OF_INPUT = "END_OF_INPUT"; char *RETURN = "RETURN";

//SINGLE PUNCTUATION
char *OPEN_PAREN = "OPEN_PAREN";	char *CLOSE_PAREN = "CLOSE_PAREN";
char *OPEN_BRACE = "OPEN_BRACE";	char *CLOSE_BRACE = "CLOSE_BRACE";
char *OPEN_BRACKET = "OPEN_BRACKET";	char *CLOSE_BRACKET = "CLOSE_BRACKET";
char *SEMICOLON = "SEMICOLON";
char *COLON = "COLON";
char *COMMA = "COMMA";

//OPERATORS
char *PLUS = "PLUS";	char *MINUS = "MINUS";	char *DIVISION = "DIVISION";
char *TIMES = "TIMES";	char *MODULO = "MODULO";	char *EXPONENT = "EXPONENT";
char *DOT = "DOT";	char *AMPERSAND = "SINGLE_AMPERSAND";
char *EQUAL_TO = "EQUAL_TO";	char *NOT_EQUAL_TO = "NOT_EQUAL_TO";
char *GREATER_THAN = "GREATER_THAN";	char *GREATER_THAN_OR_EQUAL_TO = "GREATER_THAN_OR_EQUAL_TO";
char *LESS_THAN = "LESS_THAN";	char *LESS_THAN_OR_EQUAL_TO = "LESS_THAN_OR_EQUAL_TO";
char *AND = "AND";	char *OR = "OR";	char *NOT = "NOT";	
char *EQUALS = "EQUALS";
char *PLUS_EQUALS = "PLUS_EQUALS";	char *MINUS_EQUALS = "MINUS_EQUALS";
char *TIMES_EQUALS = "TIMES_EQUALS";	char *DIVISION_EQUALS = "DIVISION_EQUALS";
char *MODULO_EQUALS = "MODULO_EQUALS";	char *EXPONENT_EQUALS = "EXPONENT_EQUALS";
char *PLUS_PLUS = "PLUS_PLUS";	char *MINUS_MINUS = "MINUS_MINUS";

//BAD TYPES
char *BAD_CHAR = "BAD_CHAR"; 	char *BAD_REAL = "BAD_REAL";	char *BAD_VAR = "BAD_VAR";
char *NON_DEFINED_SINGLE_VERTICAL_BAR = "NON_DEFINE_SINGLE_VBAR";

//PARSER
char *PROGRAM = "PROGRAM"; char *VARDEF = "VARDEF"; char *FUNCDEF = "FUNCDEF"; 
char *CLASSDEF = "CLASSDEF";
char *VARINIT = "VAR_INIT"; char *STATEMENT_LIST = "STATEMENT_LIST"; 
char *EXPR_OP = "EXPRESSION_OPERATOR"; char *EXPR_COMMA = "EXPRESSION_COMMA"; 
char *EXPR_UOP = "EXPRESS_UOP"; char *PARAM_LIST = "PARAMETER_LIST"; 
char *IFSTATE = "IF_STATEMENT"; char *WHILELOOP = "WHILE_LOOP";
char *FORLOOP = "FOR_LOOP"; char *UNARY_UOP = "UNARY_UOP"; 
char *PRINTLNSTATE = "PRINTLN_STATEMENT"; char *PRINTSTATE = "PRINT_STATEMENT"; 
char *PAREN_EXPR = "PAREN_EXPRESSION"; char *FUNCCALL = "FUNC_CALL"; 
char *EXPR_LIST = "EXPRESSION_LIST"; char *IFBLOCK = "IF_BLOCK"; 
char *FOREXPR = "FOR_EXPRESSION"; char *FORBLOCK = "FOR_BLOCK"; 
char *FUNCBLOCK = "FUNC_BLOCK"; char *OP_EXPR = "OP_EXPR";
char *PBLOCK = "PRINT_BLOCK"; char *OPTPARAMLIST = "OPT_PARAMLIST"; char *PSTATEMENT = "PRETTY_STATEMENT";
char *PASSIGN = "PRINT_ASSIGN"; char *PEXPR = "PRINT_EXPR"; char *PPARAMLIST = "PRINT_PARAMLIST"; char *PRETURN = "PRINT_RETURN";
char *UNARY = "UNARY"; char *POPERATOR = "PRINT_OP"; char *PUOP = "PRINT_UOP"; char *POPTELSE = "PRINT_ELSE"; char *POPTEXPR = "PRINT_OPTEXPR"; char *PVAREXPR = "PRINT_VAREXPR";
char *OPTEXPRLIST = "OPT_EXPRLIST"; char *PEXPRLIST = "PRINT_EXPRLIST";
char *STATEMENT = "STATEMENT"; char *CLASSCALL = "CLASS_CALL"; char *CALLCLASS = "CALL_CLASS";
char *WHILEBLOCK = "WHILE_BLOCK";

//ENVIRONMENTS
char *ENV = "ENV";	char *UNDEFINED_VAR = "UNDEFINED_VAR";
char *VALUES = "VALUES";	char *JOIN = "JOIN";

//EVALUATOR
char *CLOSURE = "CLOSURE"; char *OCLOSURE = "OCLOSURE";
char *BUILTIN = "BUILTIN"; char *GLUE = "GLUE";
char *RETURNED = "RETURNED"; char *ARRAY = "ARRAY";
char *FILEPTR = "FILEPTR"; char *LAMBDA = "LAMBDA";
char *LAMBDADEF = "LAMBDADEF";